categoriesList = [
    "abstract",
    "aircraft",
    "airplane",
    "airport",
    "alps",
    "amazon rainforest",
    "animal",
    "animals",
    "architecture",
    "arctic",
    "art",
    "astronaut",
    "barcelona",
    "beach",
    "beach sunset",
    "bee",
    "berlin",
    "bird",
    "blur",
    "business",
    "butterfly",
    "car",
    "cat",
    "china",
    "city",
    "city night",
    "climb",
    "coffee",
    "computer",
    "construction",
    "coral bay",
    "corals",
    "dark",
    "desert",
    "desert night",
    "design",
    "diving",
    "dog",
    "dubai",
    "earth",
    "electronic",
    "fall",
    "fish",
    "flowers",
    "fly",
    "forest",
    "france",
    "games",
    "garden",
    "greece",
    "guitar",
    "hotel",
    "ice",
    "iceberg",
    "iceland",
    "india",
    "insect",
    "italy",
    "japan",
    "jellyfish",
    "jungle",
    "kids",
    "korea",
    "lake",
    "landscape",
    "london",
    "london skyline night",
    "love",
    "luxury",
    "madrid",
    "map",
    "mars",
    "moon",
    "mountain",
    "mountain climbing",
    "mountain peak",
    "music",
    "nature",
    "navy",
    "new york",
    "new york night",
    "new zealand",
    "night",
    "norway",
    "ocean",
    "octopus",
    "octopus underwater",
    "outdoors",
    "painter",
    "painting",
    "paris",
    "park",
    "people",
    "planet",
    "rain",
    "railway",
    "railway station",
    "real estate",
    "renovation",
    "river",
    "road",
    "rock",
    "rome",
    "sailboat",
    "sea",
    "shark",
    "ship",
    "singapore",
    "singapore skyline",
    "sky",
    "skyline",
    "skyline at night",
    "space",
    "spaceship",
    "spain",
    "spring",
    "stars",
    "submarine",
    "summer",
    "sun",
    "sunset",
    "switzerland",
    "technology",
    "tiger",
    "tokyo",
    "tools",
    "train",
    "travel",
    "trees",
    "underwater",
    "venice",
    "wall",
    "water",
    "waterfall",
    "waves",
    "wood",
    "yacht"
];

module.exports = { categoriesList };